const CSV_URL='https://docs.google.com/spreadsheets/d/e/2PACX-1vToXcV323xvYtiuz6tg-d0q_f2iwOwnYBpCRqAgSnarQ2PYVZ9Z1GJKlSmftjuajtlJ6zBfmVbRwArp/pub?output=csv';
const WA='9647719183122',CACHE='firdaws_products_v6',$=id=>document.getElementById(id);let products=[],selectedCategory='',selectedSub='',selectedBrand='',sortMode='',priceMin=null,priceMax=null,cart=JSON.parse(localStorage.getItem('firdaws_cart')||'{}'),lockedY=0;
function applySort(list){const l=list.slice();if(sortMode==='price_asc')l.sort((a,b)=>a.price-b.price);else if(sortMode==='price_desc')l.sort((a,b)=>b.price-a.price);else if(sortMode==='name_asc')l.sort((a,b)=>a.name.localeCompare(b.name,'ar'));return l}
function applyPriceRange(list){return list.filter(p=>(priceMin==null||p.price>=priceMin)&&(priceMax==null||p.price<=priceMax))}
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++;continue}if(c==='"'){quoted=!quoted;continue}if(c===','&&!quoted){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(v=>v!==''))rows.push(row);row=[];continue}cell+=c}row.push(cell);if(row.some(v=>v!==''))rows.push(row);if(!rows.length)return[];const headers=rows.shift().map(h=>String(h).trim().toLowerCase());return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,String(r[i]??'').trim()]))) }
function num(v){const n=Number(String(v??'').replace(/[,،\s]/g,''));return Number.isFinite(n)?n:0}function truthy(v){return /^(1|true|yes|نعم)$/i.test(String(v||'').trim())}function inactive(v){return /^(0|false|no|لا|موقوف|inactive)$/i.test(String(v||'').trim())}function parseSpecs(v){return String(v||'').split('|').map(s=>s.trim()).filter(Boolean).map(pair=>{const i=pair.indexOf(':');return i>-1?[pair.slice(0,i).trim(),pair.slice(i+1).trim()]:null}).filter(Boolean)}
function normalize(rows){return rows.map(x=>{const extra=String(x.images||'').split('|').map(s=>s.trim()).filter(Boolean);return{id:String(x.id||'').trim(),name:String(x.name||'').trim(),price:num(x.price),old:num(x.old_price),offer:truthy(x.offer),note:x.discount_note||'',image:x.image||'',images:[x.image||'',...extra].filter(Boolean),specs:parseSpecs(x.specs),rating:Math.max(0,Math.min(5,Number(String(x.rating||'').replace(',','.'))||0)),reviews:num(x.reviews),isNew:truthy(x.is_new),bestseller:truthy(x.bestseller),category:x.category||'غير مصنف',sub:x.sub_category||'',brand:x.brand||'',brandLogo:x.brand_logo||'',desc:x.desc||'',active:x.active||'',stock:x.stock===''||x.stock==null?null:Math.max(0,num(x.stock))}}).filter(x=>x.id&&x.name&&!inactive(x.active))}
const sold=p=>p.stock!==null&&p.stock<=0,esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),money=n=>num(n).toLocaleString('ar-IQ');
function lockPage(){if(document.body.classList.contains('locked'))return;lockedY=window.scrollY;document.body.style.top=`-${lockedY}px`;document.body.classList.add('locked')}function unlockPage(){if(!document.body.classList.contains('locked'))return;document.body.classList.remove('locked');document.body.style.top='';window.scrollTo(0,lockedY)}function openDialog(id){lockPage();$(id).showModal()}function closeDialog(id){const d=$(id);if(d.open)d.close();if(!$('productModal').open&&!$('cartModal').open&&!$('installModal').open&&!$('policyModal').open)unlockPage()}['productModal','cartModal','installModal','policyModal'].forEach(id=>{$(id).addEventListener('cancel',e=>{e.preventDefault();closeDialog(id)});$(id).addEventListener('click',e=>{if(e.target===$(id))closeDialog(id)})});
let deferredInstallPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e});
function showInstallGuide(){const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);const standalone=window.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;if(standalone){$('installSteps').innerHTML='<div class="install-step">✓ المتجر مثبت بالفعل على جهازك.</div>';openDialog('installModal');return}if(deferredInstallPrompt){deferredInstallPrompt.prompt();deferredInstallPrompt.userChoice.finally(()=>{deferredInstallPrompt=null});return}$('installSteps').innerHTML=ios?'<div class="install-step"><span class="install-icon">⇧</span><span class="install-text">اضغط زر المشاركة أسفل Safari</span></div><div class="install-arrow">↓</div><div class="install-step"><span class="install-icon">＋</span><span class="install-text">اختر «إضافة إلى الشاشة الرئيسية»</span></div><div class="install-arrow">↓</div><div class="install-step"><span class="install-icon">✓</span><span class="install-text">اضغط «إضافة» — تم التثبيت</span></div>':'<div class="install-step"><span class="install-icon">⋮</span><span class="install-text">افتح قائمة المتصفح</span></div><div class="install-arrow">↓</div><div class="install-step"><span class="install-icon">＋</span><span class="install-text">اختر «تثبيت التطبيق» أو «إضافة إلى الشاشة الرئيسية»</span></div><div class="install-arrow">↓</div><div class="install-step"><span class="install-icon">✓</span><span class="install-text">وافق على التثبيت</span></div>';openDialog('installModal')}
function metaLinks(p){const a=[];if(p.category)a.push(`<button data-meta-category="${esc(p.category)}">${esc(p.category)}</button>`);if(p.sub)a.push(`<button data-meta-sub="${esc(p.sub)}" data-parent="${esc(p.category)}">${esc(p.sub)}</button>`);if(p.brand)a.push(`<button data-meta-brand="${esc(p.brand)}" data-parent="${esc(p.category)}">${esc(p.brand)}</button>`);return a.join('')}
function purchaseMarkup(p){const out=sold(p),qty=cart[p.id]||0;if(out)return '<button class="add" disabled>نفدت الكمية</button>';if(qty>0)return `<div class="qty-inline"><button data-qty-dec="${esc(p.id)}">−</button><b>${qty}</b><button data-qty-inc="${esc(p.id)}">+</button></div>`;return `<button class="add" data-add="${esc(p.id)}">+ أضف للسلة</button>`}
function discountPct(p){return p.old>p.price?Math.round((1-p.price/p.old)*100):0}
function cardBadges(p,out){if(out)return '<span class="sold-pill">نفدت الكمية</span>';const b=[];if(p.isNew)b.push('<span class="pill pill-new">جديد</span>');if(p.bestseller)b.push('<span class="pill pill-best">الأكثر مبيعاً</span>');const pct=discountPct(p);if(pct>0)b.push(`<span class="pill pill-off">-${pct}%</span>`);else if(p.offer)b.push('<span class="pill">عرض</span>');return b.join('')}
function starsHtml(p){if(!p.rating)return '';const f=Math.round(p.rating);return `<div class="rating"><span>${'★'.repeat(f)}${'☆'.repeat(5-f)}</span><span class="rating-num">(${p.reviews||0})</span></div>`}
function card(p){const out=sold(p);return `<article class="card${out?' soldout':''}"><div class="image-wrap" data-open="${esc(p.id)}">${cardBadges(p,out)}<img src="${esc(p.image)}" loading="lazy" alt="${esc(p.name)}"></div><div class="body"><div class="meta">${metaLinks(p)}</div><div class="title" data-open="${esc(p.id)}">${esc(p.name)}</div>${starsHtml(p)}<div class="price-row"><span class="price">${money(p.price)} د.ع</span>${p.old>p.price?`<span class="old">${money(p.old)} د.ع</span>`:''}</div>${p.note?`<div class="note">${esc(p.note)}</div>`:''}<div class="actions"><div data-purchase="${esc(p.id)}">${purchaseMarkup(p)}</div><button class="details" data-open="${esc(p.id)}">تفاصيل</button></div></div></article>`}
function renderBrands(){const seen=new Map();products.forEach(p=>{if(p.brand&&p.brandLogo&&!seen.has(p.brand))seen.set(p.brand,p.brandLogo)});const items=[...seen.entries()];$('brandLogos').innerHTML=items.map(([name,logo])=>`<button class="brand-logo-btn" data-home-brand="${esc(name)}" aria-label="${esc(name)}"><img src="${esc(logo)}" alt="${esc(name)}"></button>`).join('');$('brandShowcase').classList.toggle('hidden',!items.length)}
function renderHome(){const q=$('q').value.trim().toLowerCase();const list=products.filter(p=>!q||[p.name,p.category,p.sub,p.brand].join(' ').toLowerCase().includes(q));$('status').textContent=list.length+' منتج';$('homeGrid').innerHTML=list.map(card).join('')||'<div class="empty">لا توجد منتجات مطابقة.</div>';const offers=products.filter(p=>p.offer||p.old>p.price).slice(0,12);$('homeOffers').innerHTML=offers.map(card).join('')||'<div class="empty">لا توجد عروض حاليًا.</div>'}
function renderCategories(){const cats=[...new Set(products.map(p=>p.category).filter(Boolean))];$('categoryCount').textContent=cats.length+' قسم';$('categoryGrid').innerHTML=cats.map((c,i)=>{const count=products.filter(p=>p.category===c).length,icons=['▦','◈','◇','▣','◉','⌁'];return `<button class="category-card" data-category="${esc(c)}"><span class="category-icon">${icons[i%icons.length]}</span><strong>${esc(c)}</strong><small>${count} منتج</small></button>`}).join('')||'<div class="empty">لا توجد أقسام.</div>'}
function renderFilters(){const base=selectedCategory?products.filter(p=>p.category===selectedCategory):products,subs=[...new Set(base.map(p=>p.sub).filter(Boolean))],brands=[...new Set(base.map(p=>p.brand).filter(Boolean))];let h=`<div class="sort-row"><select id="sortSelect"><option value="">الترتيب: الافتراضي</option><option value="price_asc"${sortMode==='price_asc'?' selected':''}>السعر: الأقل أولاً</option><option value="price_desc"${sortMode==='price_desc'?' selected':''}>السعر: الأعلى أولاً</option><option value="name_asc"${sortMode==='name_asc'?' selected':''}>الاسم: أ-ي</option></select><div class="price-range"><input type="number" id="priceMinInput" placeholder="السعر من" value="${priceMin??''}"><input type="number" id="priceMaxInput" placeholder="السعر إلى" value="${priceMax??''}"></div></div>`;if(selectedCategory&&subs.length)h+=`<div class="filter-label">الأقسام الفرعية</div><div class="chips"><button class="chip ${!selectedSub?'active':''}" data-sub="">الكل</button>${subs.map(s=>`<button class="chip ${selectedSub===s?'active':''}" data-sub="${esc(s)}">${esc(s)}</button>`).join('')}</div>`;if(brands.length)h+=`<div class="filter-label">البراندات</div><div class="chips"><button class="chip ${!selectedBrand?'active':''}" data-brand="">الكل</button>${brands.map(b=>`<button class="chip ${selectedBrand===b?'active':''}" data-brand="${esc(b)}">${esc(b)}</button>`).join('')}</div>`;$('categoryFilters').innerHTML=h;$('sortSelect').onchange=e=>{sortMode=e.target.value;renderSelectedCategory()};$('priceMinInput').onchange=e=>{priceMin=e.target.value===''?null:num(e.target.value);renderSelectedCategory()};$('priceMaxInput').onchange=e=>{priceMax=e.target.value===''?null:num(e.target.value);renderSelectedCategory()}}