function renderSelectedCategory(){let list=selectedCategory?products.filter(p=>p.category===selectedCategory):products.slice();if(selectedSub)list=list.filter(p=>p.sub===selectedSub);if(selectedBrand)list=list.filter(p=>p.brand===selectedBrand);list=applyPriceRange(list);list=applySort(list);$('productsTitle').textContent=[selectedCategory,selectedSub,selectedBrand].filter(Boolean).join(' • ')||'المنتجات';$('productsCount').textContent=list.length+' منتج';renderFilters();$('productGrid').innerHTML=list.map(card).join('')||'<div class="empty">لا توجد منتجات مطابقة.</div>'}
function renderOffers(){const list=products.filter(p=>p.offer||p.old>p.price);$('offersCount').textContent=list.length+' عرض';$('offersGrid').innerHTML=list.map(card).join('')||'<div class="empty">لا توجد عروض حاليًا.</div>'}
function setView(view){['homeView','categoriesView','productsView','offersView'].forEach(id=>$(id).classList.add('hidden'));if(view==='home')$('homeView').classList.remove('hidden');if(view==='categories'){$('categoriesView').classList.remove('hidden');renderCategories()}if(view==='offers'){$('offersView').classList.remove('hidden');renderOffers()}document.querySelectorAll('.nav-btn[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo(0,0)}
function openCategory(name,sub='',brand=''){selectedCategory=name;selectedSub=sub;selectedBrand=brand;renderSelectedCategory();['homeView','categoriesView','offersView'].forEach(id=>$(id).classList.add('hidden'));$('productsView').classList.remove('hidden');document.querySelectorAll('.nav-btn[data-view]').forEach(b=>b.classList.remove('active'));window.scrollTo(0,0)}
function galleryHtml(p,out){const imgs=p.images&&p.images.length?p.images:[p.image];const thumbs=imgs.length>1?`<div class="thumbs">${imgs.map((im,i)=>`<img src="${esc(im)}" class="${i===0?'active':''}" data-thumb="${i}">`).join('')}</div>`:'';return `<img class="main-img" src="${esc(imgs[0])}" alt="${esc(p.name)}" style="${out?'filter:grayscale(1);opacity:.55':''}">${thumbs}`}
function switchThumb(i){const g=document.querySelector('.gallery');if(!g)return;const imgs=[...g.querySelectorAll('.thumbs img')],main=g.querySelector('.main-img');if(!imgs[i]||!main)return;main.src=imgs[i].src;imgs.forEach((im,idx)=>im.classList.toggle('active',idx==i))}
function specsHtml(p){if(!p.specs.length)return '';return `<table class="specs-table">${p.specs.map(([k,v])=>`<tr><td>${esc(k)}</td><td>${esc(v)}</td></tr>`).join('')}</table>`}
function optionsHtml(p){if(!p.options||!p.options.length)return'';return `<div style="margin:18px 0;padding:14px;border:1px solid #dbe4ee;border-radius:16px;background:#f8fafc"><div style="font-weight:800;margin-bottom:10px">اختر تفاصيل المنتج</div>${p.options.map(o=>`<label style="display:block;font-weight:700;font-size:13px;margin:10px 0 6px">${esc(o.name)}</label><select class="product-option-select" data-option-name="${esc(o.name)}" style="width:100%;padding:12px;border:1px solid #dbe4ee;border-radius:12px;background:#fff;font:inherit">${o.values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}</select>`).join('')}</div>`}
function selectedProductOptions(p){const out={};if(!p.options||!p.options.length)return out;p.options.forEach(o=>{const el=document.querySelector(`.product-option-select[data-option-name="${CSS.escape(o.name)}"]`);out[o.name]=el?el.value:o.values[0]});return out}
function relatedHtml(p){const rel=products.filter(x=>x.id!==p.id&&(x.category===p.category||x.brand===p.brand)).slice(0,8);if(!rel.length)return '';return `<div class="related"><h3>قد يعجبك أيضاً</h3><div class="related-strip">${rel.map(card).join('')}</div></div>`}
function shareProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const url=location.href.split('#')[0]+'#p-'+p.id,text=`${p.name} - ${money(p.price)} د.ع`;if(navigator.share){navigator.share({title:p.name,text,url}).catch(()=>{})}else if(navigator.clipboard){navigator.clipboard.writeText(url);toast('✓ تم نسخ رابط المنتج')}}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const out=sold(p);$('productContent').innerHTML=`<div class="detail"><div class="gallery">${galleryHtml(p,out)}</div><div class="info"><div class="meta">${metaLinks(p)}</div><h2>${esc(p.name)}</h2>${starsHtml(p)}<div class="price-row"><span class="price">${money(p.price)} د.ع</span>${p.old>p.price?`<span class="old">${money(p.old)} د.ع</span>`:''}</div>${out?'<div class="sold-msg">نفدت الكمية حاليًا</div>':''}${p.desc?`<div class="desc">${esc(p.desc)}</div>`:''}${specsHtml(p)}${optionsHtml(p)}<div data-purchase="${esc(p.id)}">${purchaseMarkup(p)}</div><button class="share-btn" type="button" data-share="${esc(p.id)}">↗ مشاركة المنتج</button></div></div>${relatedHtml(p)}`;openDialog('productModal')}
function cartEntry(id){const v=cart[id];if(!v)return{qty:0,options:{}};if(typeof v==='number')return{qty:v,options:{}};return{qty:Number(v.qty)||0,options:v.options||{}}}
function syncPurchase(id){const p=products.find(x=>x.id===id);if(!p)return;document.querySelectorAll(`[data-purchase="${CSS.escape(id)}"]`).forEach(el=>el.innerHTML=purchaseMarkup(p))}
function saveCart(){localStorage.setItem('firdaws_cart',JSON.stringify(cart));updateCart()}
function add(id){const p=products.find(x=>x.id===id);if(!p||sold(p))return toast('نفدت الكمية');if(p.options&&p.options.length&&!$('productModal').open){openProduct(id);return toast('اختر التفاصيل أولاً ثم أضف للسلة')}const current=cartEntry(id);if(p.stock!==null&&current.qty>=p.stock)return toast('وصلت للكمية المتوفرة');const opts=p.options&&p.options.length?selectedProductOptions(p):current.options;cart[id]={qty:current.qty+1,options:opts};saveCart();syncPurchase(id);toast('✓ تمت الإضافة للسلة')}
function inlineInc(id){const p=products.find(x=>x.id===id);if(!p||sold(p))return;const current=cartEntry(id);if(p.stock!==null&&current.qty>=p.stock)return toast('وصلت للكمية المتوفرة');cart[id]={qty:current.qty+1,options:current.options};saveCart();syncPurchase(id)}
function inlineDec(id){const current=cartEntry(id);if(!current.qty)return;current.qty--;if(current.qty<=0)delete cart[id];else cart[id]=current;saveCart();syncPurchase(id)}
function cartItems(){return Object.keys(cart).map(id=>{const p=products.find(x=>x.id===id),c=cartEntry(id);return p&&c.qty?{...p,qty:c.qty,selectedOptions:c.options}:null}).filter(Boolean)}
function updateCart(){const items=cartItems(),pieces=items.reduce((s,x)=>s+x.qty,0),total=items.reduce((s,x)=>s+x.qty*x.price,0);$('cartCount').textContent=pieces;$('bottomCartCount').textContent=pieces;$('cartPieces').textContent=pieces;$('cartTotal').textContent=money(total)+' د.ع'}
function optionSummary(x){const o=x.selectedOptions||{};return Object.entries(o).map(([k,v])=>`<div style="font-size:12px;color:#475569">${esc(k)}: <b>${esc(v)}</b></div>`).join('')}
function openCart(){const items=cartItems();$('cartItems').innerHTML=items.length?items.map(x=>`<div class="cart-item"><img src="${esc(x.image)}"><div><strong>${esc(x.name)}</strong>${optionSummary(x)}<div>${money(x.price)} د.ع</div><div class="qty"><button data-dec="${esc(x.id)}">−</button><b>${x.qty}</b><button data-inc="${esc(x.id)}">+</button></div></div><button class="remove" data-del="${esc(x.id)}">حذف</button></div>`).join(''):'<div class="empty">السلة فارغة</div>';updateCart();openDialog('cartModal')}
function inc(id){const p=products.find(x=>x.id===id);if(!p||sold(p))return;const current=cartEntry(id);if(p.stock!==null&&current.qty>=p.stock)return toast('وصلت للكمية المتوفرة');cart[id]={qty:current.qty+1,options:current.options};saveCart();syncPurchase(id);openCart()}
function dec(id){const current=cartEntry(id);current.qty--;if(current.qty<=0)delete cart[id];else cart[id]=current;saveCart();syncPurchase(id);openCart()}
function del(id){delete cart[id];saveCart();syncPurchase(id);openCart()}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),1400)}
const moneyOrder=n=>num(n).toLocaleString('en-US');
function buildOrderMessage(requireCustomer=false){const items=cartItems().filter(x=>!sold(x));if(!items.length){toast('السلة فارغة');return''}const n=$('customerName').value.trim(),p=$('phone').value.trim(),ad=$('address').value.trim(),nt=$('note').value.trim();if(requireCustomer&&(!n||!p||!ad)){toast('أكمل الاسم والهاتف والعنوان');return''}const total=items.reduce((s,x)=>s+x.qty*x.price,0);let msg=`🛍️ طلب جديد | معرض الفردوس\n━━━━━━━━━━━━━━\n\n👤 بيانات الزبون\nالاسم: ${n||'-'}\nالهاتف: ${p||'-'}\nالعنوان: ${ad||'-'}\n`;if(nt)msg+=`ملاحظات: ${nt}\n`;msg+='\n🛒 تفاصيل الطلب\n\n'+items.map((x,i)=>{const opts=Object.entries(x.selectedOptions||{}).map(([k,v])=>`${k}: ${v}`).join('\n');return `${i+1}️⃣ ${x.name}\n${opts?opts+'\n':''}الكمية: ${x.qty}\nالسعر: ${moneyOrder(x.price)} د.ع\nالمجموع: ${moneyOrder(x.qty*x.price)} د.ع`}).join('\n\n')+`\n\n━━━━━━━━━━━━━━\n💰 الإجمالي: ${moneyOrder(total)} د.ع\n\nشكراً لتسوقك من معرض الفردوس 🤍`;return msg}
async function copyOrderText(msg){try{await navigator.clipboard.writeText(msg);return true}catch(e){return false}}
function clearAllCart(){if(!cartItems().length)return toast('السلة فارغة');if(!confirm('هل تريد إفراغ السلة بالكامل؟'))return;const ids=Object.keys(cart);cart={};saveCart();ids.forEach(syncPurchase);openCart();toast('✓ تم إفراغ السلة')}
document.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close)return closeDialog(close.dataset.close);const hb=e.target.closest('[data-home-brand]');if(hb)return openCategory('','',hb.dataset.homeBrand);const mc=e.target.closest('[data-meta-category]');if(mc){if($('productModal').open)closeDialog('productModal');return openCategory(mc.dataset.metaCategory)}const ms=e.target.closest('[data-meta-sub]');if(ms){if($('productModal').open)closeDialog('productModal');return openCategory(ms.dataset.parent,ms.dataset.metaSub,'')}const mb=e.target.closest('[data-meta-brand]');if(mb){if($('productModal').open)closeDialog('productModal');return openCategory(mb.dataset.parent,'',mb.dataset.metaBrand)}const qi=e.target.closest('[data-qty-inc]');if(qi)return inlineInc(qi.dataset.qtyInc);const qd=e.target.closest('[data-qty-dec]');if(qd)return inlineDec(qd.dataset.qtyDec);const sub=e.target.closest('[data-sub]');if(sub){selectedSub=sub.dataset.sub;return renderSelectedCategory()}const br=e.target.closest('[data-brand]');if(br){selectedBrand=br.dataset.brand;return renderSelectedCategory()}const th=e.target.closest('[data-thumb]');if(th)return switchThumb(th.dataset.thumb);const sh=e.target.closest('[data-share]');if(sh)return shareProduct(sh.dataset.share);const open=e.target.closest('[data-open]');if(open){if($('productModal').open)closeDialog('productModal');return openProduct(open.dataset.open)}const addb=e.target.closest('[data-add]');if(addb&&!addb.disabled)return add(addb.dataset.add);const cat=e.target.closest('[data-category]');if(cat)return openCategory(cat.dataset.category);const i=e.target.closest('[data-inc]');if(i)return inc(i.dataset.inc);const d=e.target.closest('[data-dec]');if(d)return dec(d.dataset.dec);const r=e.target.closest('[data-del]');if(r)return del(r.dataset.del)});
document.querySelectorAll('.nav-btn[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('bottomCartBtn').onclick=openCart;$('cartBtn').onclick=openCart;$('brandHome').onclick=()=>setView('home');$('shopNow').onclick=()=>setView('categories');$('installStoreBtn').onclick=showInstallGuide;$('policyBtn').onclick=()=>openDialog('policyModal');$('menuBtn').onclick=()=>setView('categories');$('allOffers').onclick=()=>setView('offers');$('backCategories').onclick=()=>setView('categories');$('q').addEventListener('input',renderHome);
$('clearCartBtn').onclick=clearAllCart;$('instagramOrderBtn').onclick=async()=>{const msg=buildOrderMessage(false);if(!msg)return;const ok=await copyOrderText(msg);toast(ok?'✓ تم نسخ الطلب — الصقه في رسالة إنستغرام':'افتح إنستغرام وانسخ الطلب يدويًا');window.open('https://www.instagram.com/mobil.iq/','_blank')};$('checkoutForm').addEventListener('submit',e=>{e.preventDefault();const msg=buildOrderMessage(true);if(!msg)return;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(msg)}`,'_blank')});
function applyData(data){products=data;renderBrands();renderHome();renderCategories();updateCart()}function showCached(){try{const c=JSON.parse(localStorage.getItem(CACHE)||'[]');if(Array.isArray(c)&&c.length)applyData(c)}catch{}}async function load(){showCached();try{const res=await fetch(CSV_URL,{cache:'default'});if(!res.ok)throw new Error();const fresh=normalize(parseCSV(await res.text()));if(fresh.length){localStorage.setItem(CACHE,JSON.stringify(fresh));applyData(fresh)}}catch(e){if(!products.length)$('homeGrid').innerHTML='<div class="empty">تعذر تحميل المنتجات.</div>'}}load();
